import type { Metadata } from 'next'
import './globals.css'

import { Open_Sans } from 'next/font/google'
 
const inter = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-open`}>{children}</body>
    </html>
  )
}
